import {loadFont as lf, loadStyle as ls/*, loadScript as lsc*/} from './utils/functions.js'
import {db} from './utils/const.js'
import {subaction} from './index.js'

let d = 'work';

export function styles() {
	ls(d, 'Page/base.min');
	lf(d, 'TensorFont');
	lf(d, 'TensorFontBold');
	lf(d, 'cbuc-icons');
	lf(d, 'cbuc-icons24');
	lf(d, 'MaisonNeue');
	lf(d, 'MaisonNeueBold');
	lf(d, 'Accordion-Font');
	lf(d, 'Accordion-Font-20');
	lf(d, 'MaisonNeueExtendedDemi');
	lf(d, 'MaisonNeueExtendedBook');
	db.classList.add('ws-is-chrome', 'ws-is-windows-10', 'ws-is-desktop-platform', 'zIndex-context', 'ws-is-no-touch', 'ws-is-no-drag', 'Application-body', 'controls_theme-default', 'ru', 'ru-RU', 'nanomagicPage-MainLayout__body', 'ws-is-adaptive', 'undefined', 'ws-is-hover');
	db.dir = 'ltr';
	let r = document.getElementById('nanomagic-content')
	r.style.width = '100%';
	r.style.height = '100%';
	r.style.display = 'contents';
	ls(d, 'ThemesModule/default.min');
	ls(d, 'ThemesModule/onlinenavigation.min');
	ls(d, 'NoticeCenterRoute/panelView.min');
	ls(d, 'Emoji/base.min');
	ls(d, 'Controls/controls-superbundle.package.min');
	ls(d, 'Page/page-superbundle.package.min');
	ls(d, 'Hint/page-superbundle.package.min');
	ls(d, 'EventRibbon/EventRibbon.package.min');
	ls(d, 'NavigationPanels/base-superbundle.package.min');
	ls(d, 'Controls/decorator.min');
	ls(d, 'Tailwind/tailwind.min');
	ls(d, 'NanoMagicPage/contentLayout.min');
	ls(d, 'NanoMagicPage/widgets.min');
	ls(d, 'NanoMagicPage/widgets/RightPanel.min');
	ls(d, 'ViewSettings/controller.min');
	ls(d, 'NanoMagicPage/mainLayout.min');
	ls(d, 'GeneralSearch/Search/Search.min');
	ls(d, 'Controls/input.min');
	ls(d, 'Controls/search.min');
	ls(d, 'Controls/suggest.min');
	ls(d, 'Controls/dropdown.min');
	ls(d, 'Controls/toolbars.min');
	ls(d, 'Controls/operations.min');
	ls(d, 'Controls/filter.min');
	ls(d, 'Controls/paging.min');
	ls(d, 'Controls/validate.min');
	ls(d, 'Dashboard/dashboard.min');
	ls(d, 'Dashboard/page.min');
	ls(d, 'EngineUser/UserStatus.min');
	ls(d, 'SiteEditorBase/_player/View.min');
	ls(d, 'SiteEditorBase/_widgets/BaseDecorator.min');
	ls(d, 'Dashboard/runtime.min');
	ls(d, 'NoticeCenter/dashboard.min');
	ls(d, 'Controls/heading.min');
	ls(d, 'Controls/popupTemplate.min');
	ls(d, 'Controls/progress.min');
	ls(d, 'ExtControls/floatingToolbar.min');
	ls(d, 'Controls/skeleton.min');
	ls(d, 'LinkDecorator/view.min');
	ls(d, 'Controls/CustomColors.min');
	ls(d, 'RichEditor/base.min');
	ls(d, 'NoticeCenterBase/noticeControls.min');
	ls(d, 'Controls/itemActions.min');
	ls(d, 'NoticeCenter/panelView.min');
	ls(d, 'NoticeCenter/settingsView.min');
	ls(d, 'NoticeCenter/widgets.min');
	ls(d, 'Controls/checkbox.min');
	ls(d, 'Controls/toggle.min');
	ls(d, 'Motivation/Controls/_emptyView/WidgetEmptyView/WidgetEmptyView.min');
	ls(d, 'Person/photo.min');
	ls(d, 'Person/information.min');
	ls(d, 'MotivationNotice/controls.min');
	ls(d, 'MotivationNotice/userNotices.min');
	ls(d, 'Motivation/Ratings/Controls/_participantsPhotoLine/ParticipantsPhotoLine.min');
	ls(d, 'Motivation/Ratings/_widget/RatingNoticeCenter.min');
	ls(d, 'Controls/baseList.min');
	ls(d, 'EntityWidget/view.min');
	ls(d, 'HowEasy/view.min');
	ls(d, 'Controls/tabs.min');
	ls(d, 'Controls/date.min');
	ls(d, 'Controls/dateRange.min');
	ls(d, 'Graphs/HighChartsLight.min');
	ls(d, 'Graphs/ColumnChart.min');
	ls(d, 'Graphs/LinearChart.min');
	ls(d, 'Graphs/baseChart.min');
	ls(d, 'Graphs/Infoblock.min');
	ls(d, 'Graphs/comparison.min');
	ls(d, 'MoneyWidgets/graph.min');
	ls(d, 'Warehouse_Stats/WarehouseStats/Widgets/Common.min');
	ls(d, 'NavigationPanels/Logotype.min');
	ls(d, 'NavigationPanels/quickadd.min');
	ls(d, 'Controls/sorting.min');
	ls(d, 'NoticeCenter/buttons.min');
	ls(d, 'Docflow/informer.min');
	ls(d, 'Informers/bar.min');
	ls(d, 'News/feed.min');
	ls(d, 'News/styles/Feed.min');
	ls(d, 'NewsCommon/List/List.min');
	ls(d, 'SbisEnvUI/header.min');
	ls(d, 'SbisEnvUI/parking.min');
	if (['tasks-in-work', 'tasks-from-me'].includes(subaction)) {
		ls(d, 'EDWS3/Tasks/Registry/InWork/InWork.min');
		ls(d, 'EDWS3/Tasks/_transfer/Button.min');
		ls(d, 'EDWS3/Tasks/MasterDetail/MasterDetail.min');
		ls(d, 'EDWS3/Tasks/TopButtons/TopButtons.min');
		ls(d, 'EDWS3/Tasks/Tabs/Tabs.min');
		ls(d, 'EDWS3/Tasks/MasterView/MasterView.min');
		ls(d, 'EDO3Core/browserTemplates.min');
		ls(d, 'Controls/grid.min');
		ls(d, 'Controls/masterDetail.min');
		ls(d, 'Controls/treeGrid.min');
		ls(d, 'EDO3/Marks/Styles.min');
		ls(d, 'EDO3/browser.min');
		ls(d, 'Message/search.min');
		ls(d, 'Controls/list.min');
		ls(d, 'EDO3/actions.min');
		ls(d, 'Layout/layout-browser.package.min');
		ls(d, 'EntityChoice/utils.min');
		ls(d, 'EDWS3/Tasks/Registry/Registry.min');
		ls(d, 'Controls/lookup.min');
		ls(d, 'Layout/Selector.min');
		ls(d, 'Person/_popup/PreviewController.min');
		ls(d, 'Hint/_resources/ExtendedHelpButton/ExtendedHelpButton.min');
		ls(d, 'Controls/filterPanelPopup.min');
		ls(d, 'Controls/filterPopup.min');
		ls(d, 'Controls/menu.min');
		ls(d, 'EDO3/filter.min');
		ls(d, 'EDO3/Rule/Pass/Chooser.min');
		ls(d, 'Controls/suggestPopup.min');
		ls(d, 'EDO3/Rule/Phase/Chooser.min');
		ls(d, 'Addressee/field.min');
		ls(d, 'EDWS3/Docs/Contracts/SelectorButton/SelectorButton.min');
		ls(d, 'DOCVIEW3Core/preview.min');
		ls(d, 'EDO3/cloud.min')
	}
	if (subaction === 'documents-all') {
		ls(d, 'Controls/menu.min');
		ls(d, 'Controls/list.min');
		ls(d, 'SaleScripts/IndicatorButton.min');
		ls(d, 'CoreUserCalendar/accordion.min');
		ls(d, 'Controls/calendar.min');
		ls(d, 'SDDocuments/pageContent.min');
		ls(d, 'SDDocuments/diskRegistry.min');
		ls(d, 'SDDocuments/header.min');
		ls(d, 'DOCVIEW3Core/commands.min');
		ls(d, 'DOCVIEW3/diskTemplates.min');
		ls(d, 'DOCVIEW3/diskList.min');
		ls(d, 'DOCVIEW3Core/_downloadMenuItem/View.min');
		ls(d, 'Controls/grid.min');
		ls(d, 'Controls/treeGrid.min');
		ls(d, 'SDDocuments/fastAccess.min');
		ls(d, 'SDDocuments/headerLayout.min');
		ls(d, 'Controls-widgets/newBrowser.min');
		ls(d, 'Controls/listTemplates.min');
		ls(d, 'DOCVIEW3Core/list.min');
		ls(d, 'Controls/breadcrumbs.min');
		ls(d, 'DOCVIEW3Core/preview.min');
		ls(d, 'DOCVIEW3/IconControls/Signs/Signs.min');
		ls(d, 'Controls/explorer.min');
		ls(d, 'Controls/lookup.min');
		ls(d, 'File/ResourceGetter/resourceGetter.min');
		ls(d, 'SbisFile/ResourceGetter/_DropArea/style.min');
		ls(d, 'Layout/Selector.min');
		ls(d, 'Layout/layout-browser.package.min');
		ls(d, 'Controls/masterDetail.min');
	}
}

export function tasksStyle() {
	ls(d, 'EDO3/document.min');
	ls(d, 'EDO3/toolbar.min');
	ls(d, 'ExtControls/buttons.min');
	ls(d, 'HRCore/Styles.min');
	ls(d, 'Recruitment/VacancyEnquiry/document.min');
	ls(d, 'Controls/spoiler.min');
	ls(d, 'Department/_info/Path.min');
	ls(d, 'EDO3/Document/Sticker.min');
	ls(d, 'HR/Source/icon.min');
	ls(d, 'Controls/breadcrumbs.min');
	ls(d, 'EDO3/Document/mainTabHeader.min');
	ls(d, 'EDO3/Document/tabHeaderWrapper.min');
	ls(d, 'EDO3/attachments.min');
	ls(d, 'Controls/editableArea.min');
	ls(d, 'DOCVIEW3Core/fullviewer.min');
	ls(d, 'DOCVIEW3Core/list.min');
	ls(d, 'EDO3/Document/_ruleChanger/RuleChanger.min');
	ls(d, 'File/ResourceGetter/resourceGetter.min');
	ls(d, 'SbisFile/ResourceGetter/_DropArea/style.min');
	ls(d, 'DOCVIEW3Core/viewModeSwitcher.min');
	ls(d, 'DOCVIEW3Core/Fullviewer/_tableView/View.min');
	ls(d, 'Controls/explorer.min');
	ls(d, 'DOCVIEW3Core/view.min');
}